services:
  phpsocketio:
    build: .
    ports:
      - "2026:2026"
      - "2027:2027"
    volumes:
      - .:/app
    restart: unless-stopped
    tty: false
    stdin_open: false

  rooms:
    build: .
    ports:
      - "2030:2030"
      - "2031:2031"
    volumes:
      - .:/app
    command: sh -c "composer install --no-dev --optimize-autoloader --no-interaction && php examples/rooms/start.php start"
    restart: unless-stopped
    tty: false
    stdin_open: false

  ack:
    build: .
    ports:
      - "2032:2032"
      - "2033:2033"
    volumes:
      - .:/app
    command: sh -c "composer install --no-dev --optimize-autoloader --no-interaction && php examples/ack/start.php start"
    restart: unless-stopped
    tty: false
    stdin_open: false

  namespaces:
    build: .
    ports:
      - "2034:2034"
      - "2035:2035"
    volumes:
      - .:/app
    command: sh -c "composer install --no-dev --optimize-autoloader --no-interaction && php examples/namespaces/start.php start"
    restart: unless-stopped
    tty: false
    stdin_open: false

  phpcs:
    build: .
    volumes:
      - .:/app
    command: sh -c "composer install --no-interaction && vendor/bin/phpcs src/"
    profiles: [tools]

  phpunit:
    build: .
    volumes:
      - .:/app
    command: sh -c "composer install --no-interaction && vendor/bin/phpunit"
    profiles: [tools]